export const GET_DATA_REQUEST="GETDATA_REQUEST";
export const GET_DATA_SUCCESS="GETDATA_SUCCESS";
export const GET_DATA_FAILURE="GETDATA_FAILURE";

export const GETSINGLE_DATA_REQUEST="GETSINGLEDATA_REQUEST";
export const GETSINGLE_DATA_SUCCESS="GETSINGLEDATA_SUCCESS";
export const GETSINGLE_DATA_FAILURE="GETSINGLEDATA_FAILURE";

export const ADDTOBAG_REQUEST="ADDTOBAG_REQUEST";
export const ADDTOBAG_SUCCESS="ADDTOBAG_SUCCESS";
export const ADDTOBAG_FAILURE="ADDTOBAG_FAILURE";

export const GET_BAGDATA_REQUEST="GETBAGDATA_REQUEST";
export const GET_BAGDATA_SUCCESS="GETBAGDATA_SUCCESS";
export const GET_BAGDATA_FAILURE="GETBAGDATA_FAILURE";

export const DELETE_BAGDATA_REQUEST="DELETEBAGDATA_REQUEST";
export const DELETE_BAGDATA_SUCCESS="DELETEBAGDATA_SUCCESS";
export const DELETE_BAGDATA_FAILURE="DELETEBAGDATA_FAILURE";

export const UPDATE_BAGDATA_REQUEST="UPDATEBAGDATA_REQUEST";
export const UPDATE_BAGDATA_SUCCESS="UPDATEBAGDATA_SUCCESS";
export const UPDATE_BAGDATA_FAILURE="UPDATEBAGDATA_FAILURE";