export const GET_DATA_REQUEST="GETDATA_REQUEST";
export const GET_DATA_SUCCESS="GETDATA_SUCCESS";
export const GET_DATA_FAILURE="GETDATA_FAILURE";

export const GETSINGLE_DATA_REQUEST="GETSINGLEDATA_REQUEST";
export const GETSINGLE_DATA_SUCCESS="GETSINGLEDATA_SUCCESS";
export const GETSINGLE_DATA_FAILURE="GETSINGLEDATA_FAILURE";